global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'odoo-vm1'
    static_configs:
      - targets: ['52.184.80.14:8069']
        labels:
          vm: 'vm1'
          app: 'odoo'

  - job_name: 'odoo-vm2'
    static_configs:
      - targets: ['20.189.114.223:8069']
        labels:
          vm: 'vm2'
          app: 'odoo'

  - job_name: 'moodle-vm1'
    static_configs:
      - targets: ['52.184.80.14:8080']
        labels:
          vm: 'vm1'
          app: 'moodle'

  - job_name: 'moodle-vm2'
    static_configs:
      - targets: ['20.189.114.223:8080']
        labels:
          vm: 'vm2'
          app: 'moodle'

  - job_name: 'traefik'
    static_configs:
      - targets: ['localhost:8081']
        labels:
          app: 'traefik'