# traefik/dynamic.yml
http:
  routers:
    odoo-router:
      rule: "PathPrefix(`/`)"
      entryPoints:
        - odoo
      service: odoo-loadbalancer

    moodle-router:
      rule: "PathPrefix(`/`)"
      entryPoints:
        - moodle
      service: moodle-loadbalancer

  services:
    odoo-loadbalancer:
      loadBalancer:
        sticky:
          cookie:
            name: odoo_sticky
            secure: false
        servers:
          - url: "http://52.184.80.14:8069"
          - url: "http://20.189.114.223:8069"
        healthCheck:
          path: /web/health
          interval: 10s
          timeout: 3s

    moodle-loadbalancer:
      loadBalancer:
        sticky:
          cookie:
            name: moodle_sticky
            secure: false
        servers:
          - url: "http://52.184.80.14:8080"
          - url: "http://20.189.114.223:8080"
        healthCheck:
          path: /login/index.php
          interval: 10s
          timeout: 3s