# traefik/traefik.yml
entryPoints:
  web:
    address: ":80"
  odoo:
    address: ":8069"
  moodle:
    address: ":8080"

api:
  dashboard: true
  insecure: true

providers:
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

log:
  level: INFO

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true